logger:
  file:
    path: /opt/open5gs/var/log/open5gs/amf.log
  # level: info   # fatal|error|warn|info(default)|debug|trace


global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

amf:
  sbi:
    server:
      - dev: eth1
        port: 8080
    client:
      nrf:
         - uri: http://10.40.1.2:8080
  ngap:
    server:
      - dev: eth2
  metrics:
    server:
      - dev: eth3
        port: 9090
  guami:
    - plmn_id:
        mcc: 206
        mnc: 01
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 206
        mnc: 01
      tac: 1
  plmn_support:
    - plmn_id:
        mcc: 206
        mnc: 01
      s_nssai:
        - sst: 1
          sd: abcdef
  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
    full: Open5GS
    short: Next
  amf_name: open5gs-amf0
  time:
#    t3502:
#      value: 720   # 12 minutes * 60 = 720 seconds
    t3512:
      value: 540    # 9 minutes * 60 = 540 seconds

