logger:
  file:
    path: /opt/open5gs/var/log/open5gs/nrf.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

nrf:
  sbi:
    server:
      - dev: eth1  #10.40.1.2
        port: 8080
