db_uri: mongodb://localhost/open5gs
logger:
  file:
    path: /opt/open5gs/var/log/open5gs/udr.log
  # level: info   # fatal|error|warn|info(default)|debug|trace


global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

udr:
  sbi:
    server:
      - dev: eth1
        port: 8080
    client:
      nrf:
        - uri: http://10.40.1.2:8080
